### ISSUE TITLE
Breakpoints are not hit without "stopOnEntry" : true

### ISSUE THREAD

**Issue by willi1s** [harold-b/vscode-duktape-debug#13]
If a breakpoint is set in the start of script with `"stopOnEntry": false`, the code runs before the breakpoint is set. It works ok with `"stopOnEntry": true`. The log appears to show a breakpoint being set after the resume command

Log as follows:

> Establishing connection with Duktape at 192.168.1.80:9091
Connected. Verifying protocol...
Protocol: 1 10600 v1.6.0 Sepura terminal
Requesting target info...
OUT -> <REQ: 1> <0x10: BASICINFO>
Status Notification: PAUSE
IN <- <REP: 2> <int: 10600> <str: v1.6.0> <str: Sepura terminal> <int: 1> <int: 4> <EOM: 0> 
10600 v1.6.0 Sepura terminal Little
Attached to duktape debugger.
Finalized Initialization.
removeAllTargetBreakpoints
OUT -> <REQ: 1> <0x17: LISTBREAK>
[FE] setBreakPointsRequest
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 0> <EOM: 0> 
OUT -> <REQ: 1> <0x13: RESUME>
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x18: ADDBREAK>

**Comment by harold-b** [comment]
This was by design in order to not freeze out the target device while attaching by forcing it to remain paused whilst the breakpoints are messages are handled. Stop on entry is the way to go if you need breakpoints to be set on attach.

You mentioned on the other issue getting stuck with the UI freeze issue when pressing continue -- I'll see if I can post a new version by tomorrow to see if that solves it for your issue and be able to use stopOnEntry without that issue.

**Comment by willi1s** [comment]
Understood. My implementation uses the sample duktape debug code which waits for a connection before running the code, so I've never tried attaching to a running context, hence I had not considered the case where the target would be interrupted by the debugger in order to set break points. Now that #12 is fixed this issue will no longer cause me a problem.

Thanks for the explaination
