### ISSUE TITLE
Errors when running vscode with duktape

### ISSUE THREAD

**Issue by madanagopaltcomcast** [harold-b/vscode-duktape-debug#38]
Team,

I am trying to integrate VSCode with duktape, with the vscode-duktape-debug plugin . We are facing below problem :

1,On clicking a object within a structure, values are displayed as heapptr and not as absolute values.

Eg:
**id : <cls : 6, ptr : 0x0000000001fabc40>** and not printing the actual value. 

2,Also, we sometimes facing a problem where vscode console is showing error as below:

**document not defined in document.event call from bluebird.js:835**

Please share if you have any suggestions on this.

Thanks.

Regards,
Madan

**Comment by harold-b** [comment]
Thanks for the info. The pointer address being printed should be fixed in master, if I recall. However, I haven't had the time to properly test it yet. There's also some updates that need to be done with the compatibility layer with newer versions of VSCode as well. So please bare with me and forgive the inconvenience until I'm able to get back to this.

**Comment by andrewrch** [comment]
Hi @madanagopaltcomcast can you test latest if this is still relevant and let me know if this is fixed for you?

**Comment by andrewrch** [comment]
Since this is an old issue, I'm going to resolve this. Please reopen if you're still having the same issue.
