### ISSUE TITLE
Unverified Breakpoint

### ISSUE THREAD

**Issue by AdamHarte** [harold-b/vscode-duktape-debug#5]
When I attach the debugger and set a breakpoint in VS Code, the point goes grey and says "Unverified Breakpoint". I believe I have set up my launch config correctly pointing to the right localRoot etc.

I am using JavaScript not TypeScript, and here is my launch config:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Attach",
			"type": "duk",
			"request": "attach",
			"address": "localhost",
			"port": 9091,
			"localRoot": "${workspaceRoot}",
			"sourceMaps": false,
			"outDir": null,
			"stopOnEntry": false
		}
	]
}
```
This could be an issue at the DukTape side, or maybe a problem with the extension not finding the source folder?

**Comment by harold-b** [comment]
Breakpoints are only verified when the Duktape runtime returns the response message acknowledging that a breakpoint has been set on the specified file. 

So this issue could mean that the way the file names are being loaded on the runtime might not reflect the way the files are laid out on the `localRoot`. That is, when setting a breakpoint the debugger extension will send message with the relative path from `localRoot` as the file name. If, when loading said file on the runtime, the file name was not set in that same manner, then it won't be able to set the breakpoint.

*Note: If I recall, the extension always uses forward slashes "/" for file names on all platforms.*

It could also always mean a bug on the extension as well. I haven't used regular .js files to debug in a long while so it could be that too. Though the user on #3 reported that it works, and he's using non-transpiled js.

That said, I'd resolve #4 first because I reckon that's probably the cause as the debug protocol had some  substantial changes since.
